KerasJson: KERAS_1layer.json
KerasH5:   KERAS_1layer_weights.h5
InputData: KERAS_1layer_input_features.dat
OutputPredictions:  KERAS_1layer_predictions.dat
OutputDir: KERAS-1layer-hls
ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
